### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by czqhubu** [rome753/webrtc-android-tutorial#2]
webrtc 新手，请教一下视频问题，请问如何获取手机端的视频流，保存为图片，还有音频流呢，谢谢了

**Comment by rome753** [comment]
视频数据回调在CameraCapturer的onTextureFrameCaptured方法中，音频数据在WebRtcAudioRecord的AudioRecord录制声音方法中。

**Comment by czqhubu** [comment]
谢谢了
